name: pyinla
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - annotated-types=0.6.0=py311h06a4308_0
  - black=24.8.0=py311h38be061_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2024.8.30=py311h06a4308_0
  - cffi=1.16.0=py311h5eee18b_1
  - cfgv=3.4.0=py311h06a4308_0
  - click=8.1.7=py311h06a4308_0
  - colorama=0.4.6=py311h06a4308_0
  - contourpy=1.3.0=py311hd18a35c_1
  - coverage=7.6.1=py311h9ecbd09_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - distlib=0.3.8=py311h06a4308_0
  - exceptiongroup=1.2.0=py311h06a4308_0
  - expat=2.6.3=h6a678d5_0
  - filelock=3.13.1=py311h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.51.0=py311h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - identify=2.5.5=py311h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - isort=5.13.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.4=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran-ng=8.2.0=hdf63c60_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libglib=2.78.4=hdc74915_0
  - libiconv=1.16=h5eee18b_3
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm14=14.0.6=hdb19cb5_3
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.9.1=py311h38be061_1
  - matplotlib-base=3.9.1=py311h74b4f7c_2
  - mypy_extensions=1.0.0=py311h06a4308_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nodeenv=1.7.0=py311h06a4308_0
  - numpy=2.1.1=py311h71ddf71_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - packaging=24.1=py311h06a4308_0
  - pathspec=0.10.3=py311h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pillow=10.4.0=py311h5eee18b_0
  - pip=24.2=py311h06a4308_0
  - platformdirs=3.10.0=py311h06a4308_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - ply=3.11=py311h06a4308_0
  - pre-commit=3.8.0=pyha770c72_1
  - pre_commit=3.8.0=hd8ed1ab_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.9.1=pyhd8ed1ab_0
  - pydantic-core=2.23.3=py311h9e33e62_0
  - pyparsing=3.1.2=py311h06a4308_0
  - pyqt=5.15.10=py311h6a678d5_0
  - pyqt5-sip=12.13.0=py311h5eee18b_0
  - pytest=8.3.3=pyhd8ed1ab_0
  - pytest-cov=5.0.0=pyhd8ed1ab_0
  - pytest-mpi=0.6=pyhd8ed1ab_0
  - python=3.11.9=h955ad1f_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python_abi=3.11=2_cp311
  - pyyaml=6.0.1=py311h5eee18b_0
  - qhull=2020.2=hdb19cb5_2
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h5eee18b_0
  - ruff=0.6.4=py311hef32070_0
  - scipy=1.14.1=py311he1f765f_0
  - setuptools=72.1.0=py311h06a4308_0
  - sip=6.7.12=py311h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py311h06a4308_0
  - tornado=6.4.1=py311h5eee18b_0
  - typing-extensions=4.11.0=py311h06a4308_0
  - typing_extensions=4.11.0=py311h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - ukkonen=1.0.1=py311hdb19cb5_0
  - unicodedata2=15.1.0=py311h5eee18b_0
  - virtualenv=20.26.1=py311h06a4308_0
  - wheel=0.43.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
prefix: /home/vmaillou/.conda/envs/pyinla
